### PR TITLE
Fix: similar colour values shown in `create_dist()`

### LINKED ISSUE #4: Distribution plot - colour mapping not aligned with specified bins
When we specify the intended bins range to the functions - afterhours_dist(), collaboration_dist() and  create_hist(),  colour for the last two bins range is same, default bins is working perfect.

 Please refer the below examples.

<b> Ex:1 </b> Same intensity of red colour displayed for 25 - 35 hours and 35 + hours range 

image

<b> Ex:2 </b> Same intensity of red colour displayed for 10 - 15 hours and 15 + hours range, so not able to visualise the data  

image

<b> Ex:3 </b> Default bins, no issue .

image

### PR DESCRIPTION
**Pull request by mallikharjun07**
# Summary
This pull request is implemented as a fix to #4, where the solution is to update `heat_colours()`. 

`heat_colours()` function return colours are not distinguishable with human eye even the hex decimal colour codes are different it is due to the hue and saturation ranges which are used in the function logic. So changed the logic of hue value generation. 

# Changes
The changes made in this PR are:
Original 
```
## Move from red to green
  pre_h <- seq(from = 0, to = 0.3, length.out = n - 1)
  h <- c(1, pre_h)
```

image

After change
```
## Move from red to green
  h <- seq(from = 0, to = 0.3, length.out = n)
  # h <- c(1, pre_h)
```
image

# Checks
- [x] All R CMD checks pass 
- [x] `roxygen2::roxygenise()` has been run prior to merging to ensure that `.Rd` and `NAMESPACE` files are up to date.
- [x] `NEWS.md` has been updated.

# Notes
This fixes #4.

### CODE REVIEW

**Comment by moralec** [comment]
Thanks for spotting this issue and great way to solve it [mallikharjun07](https://github.com/mallikharjun07)

**Comment by martinctc** [comment]
Thanks @mallikharjun07, looking great! I have updated `NEWS.md` as well as incremented the package version. 

Can you please sign the CLA above and after we can merge the pull request?

**Comment by mallikharjun07** [comment]
> @microsoft-github-policy-service agree [company="{your company}"]

**Comment by mallikharjun07** [comment]
@microsoft-github-policy-service agree company="HCL"

**Pull request merged**
