### PR TITLE
Feature: add ONA functionality

### PR DESCRIPTION
**Pull request by martinctc**
# Summary
This branch introduces new functionality to perform organizational network analysis (ONA) on Viva Insights data, specifically the group-to-group query (`g2g_data`) and the person-to-person query (`p2p_data`). 

The following is an example output, which takes a simulated dataset (generated with `p2p_data_sim()`), and constructs the following network plot with `network_p2p()`. 
```R
network_p2p(data = p2p_df, style = "ggraph")
```
image

# Changes
The changes made in this PR are:

## New functions
1. Added the `p2p_data` and `g2g_data` sample datasets. There is also an option to simulate a person-to-person dataset using `p2p_data_sim()`. 
2. Added `network_g2g()`.
3. Added `network_p2p()`
4. Added `network_summary()`, which is used in the `centrality` feature within `network_p2p()`. 
5. Added `create_sankey()`, which is used to generate the sankey visualization within `network_p2p()`.

## Other changes
1. Version is incremented to the development version `0.3.1.9000`. 
2. The dependency `networkD3` is added for `create_sankey()`. 
3. The dependency on `leiden` is removed, as `igraph` now has the capability to perform leiden community detection.
4. The `palette` argument currently controls the colour palette used on nodes for both the `ggraph` and `igraph` implementation. 

## Comparison with `wpa::network_p2p()`
For `vivainsights::network_p2p()`, there are several improvements from its predecessor: 

1. There is now a `centrality` argument that enables centrality to be computed and visualized as the node sizes in the network plot. This is a wrapper around `network_summary()`.  
5. The argument `algorithm`, which controls the layout algorithm, is now renamed as `layout` to be more intuitive. 
6. The API is now more consistent and intuitive, where the network plotting mechanism is now directly controlled with the `style` argument, and whether plots are generated interactively or saved as PDF is directly controlled by the values in the `return` argument. 
7. A large number of community detection algorithms from `igraph` are now available. Here is the full list: 
  - `"louvain"`
  - `"leiden"`
  - `"edge_betweenness"`
  - `"fast_greedy"`
  - `"fluid_communities"`
  - `"infomap"`
  - `"label_prop"`
  - `"leading_eigen"`
  - `"optimal"`
  - `"spinglass"`
  - `"walk_trap"`

# Checks
- [x] All R CMD checks pass 
- [x] `roxygen2::roxygenise()` has been run prior to merging to ensure that `.Rd` and `NAMESPACE` files are up to date.
- [x] `NEWS.md` has been updated.

# Example outputs

The following plot visualizes the communities identified with the 'leiden' algorithm. It uses the 'ggraph' style of plotting, which is more computationally intensive but is generally more aesthetically pleasing. The resolution parameter is set to 0.1, which would yield fewer communities. 
```R
network_p2p(
  data = p2p_df,
  community = "leiden",
  style = "ggraph",
  comm_args = list("resolution" = 0.1)
)
```
image

The following plot builds on the above by scaling the size of the nodes in proportion to their betweenness centrality.
```R
network_p2p(
  data = p2p_df,
  community = "leiden",
  centrality = "betweenness",
  style = "ggraph",
  comm_args = list("resolution" = 0.1)
)
```
image

### CODE REVIEW

**Comment by moralec** [comment]
Did a quick review today. All looking great on the g2g front,. Only minor comments:

1. g2g_network -> This alternative way of calling the function used to exist on wpa but the link is absent on this pull request. Should we add it in case someone needs to run old code?
2. I wonder if we should change the  default algo from fr to nicely. Nicely uses a method to choose the one that works best.

**Comment by moralec** [comment]
Notes on testing. 

- Replace p2pdataset with the simulated as the default. 
- change algorithm parameter to layout. 
- Standardize palette across igraph and ggraph
- increase link thickness on ggplot
- Fix centrality integration. 
-- Return data is giving the centrality measures even if centrality is off. 
-- Instead of ON / OFF, user should specify desired centrality. 
-- Table, Network, Data will continue to operate as ON / OFF -> always return all centrality measures
-- Plot and plot pdf -> edge size drawn proportionally to the chosen centrality measure. 
-- Centrality should also work when communities are on. We need to test this.

**Comment by moralec** [comment]
The original spec is here: https://github.com/microsoft/wpa/issues/225

**Comment by martinctc** [comment]
Just getting back on your feedback @moralec - thank you for going through them!

> 1. g2g_network -> This alternative way of calling the function used to exist on wpa but the link is absent on this pull request. Should we add it in case someone needs to run old code?

Will deprecate `g2g_network()` as it was previously only available on the 'wpa' package to be backward compatible with previous versions. Similarly, `p2p_network()` is deprecated. So the standardised way to call these functions is `network_g2g()` and `network_p2p()`

> 2. I wonder if we should change the  default algo from fr to nicely. Nicely uses a method to choose the one that works best.

We can test and discuss the change of the layout algorithm to "nicely". Will log this as an issue to investigate in the next version of the ONA functions. 

> Replace p2pdataset with the simulated as the default.

Currently looking at creating a better simulated dataset to replace `p2p_data`. In the mean time, the function examples will make use of an output generated by `p2p_data_sim()`; however, it's worth noting that this output does not simulate the strong and diverse tie scores. 

> change algorithm parameter to layout.

This has been updated. The argument to change the layout algorithm is now `layout`.

> Standardize palette across igraph and ggraph

This is an outstanding fix. 

> increase link thickness on ggplot

This has been updated.
 
> Fix centrality integration.
> -- Return data is giving the centrality measures even if centrality is off.
> -- Instead of ON / OFF, user should specify desired centrality.
> -- Table, Network, Data will continue to operate as ON / OFF -> always return all centrality measures
> -- Plot and plot pdf -> edge size drawn proportionally to the chosen centrality measure.
> -- Centrality should also work when communities are on. We need to test this.

This has been updated.

**Pull request merged**
